# Generated by Django 3.2.2 on 2021-05-08 15:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('adminPortal', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Announcement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mssg', models.TextField(null=True)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Student_Timetable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('excel_file', models.FileField(blank=True, default='timetable/blank.xlsx', null=True, upload_to='timetable/students')),
                ('std', models.IntegerField(unique=True)),
            ],
            options={
                'ordering': ['std'],
            },
        ),
        migrations.RemoveField(
            model_name='announcements',
            name='user',
        ),
        migrations.DeleteModel(
            name='Timetable',
        ),
        migrations.DeleteModel(
            name='Announcements',
        ),
    ]
