# Generated by Django 3.2.2 on 2021-05-08 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminPortal', '0002_auto_20210508_2041'),
    ]

    operations = [
        migrations.AddField(
            model_name='announcement',
            name='is_open',
            field=models.BooleanField(default=True),
        ),
    ]
