# Generated by Django 3.2.2 on 2021-05-08 15:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('studentPortal', '0002_alter_student_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Assignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('std', models.IntegerField()),
                ('subject', models.CharField(choices=[('Math', 'Math'), ('Science', 'Science'), ('History', 'History'), ('Geography', 'Geography'), ('Economics', 'Economics'), ('English', 'English'), ('Hindi', 'Hindi'), ('EVS', 'EVS'), ('GK', 'GK'), ('Art and Craft', 'Art and Craft')], max_length=30)),
                ('mssg', models.CharField(max_length=500)),
                ('date', models.DateField(auto_now_add=True)),
                ('deadline', models.DateField()),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('age', models.IntegerField()),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='teacher', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Teacher_Timetable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('excel_file', models.FileField(blank=True, default='timetable/blank.xlsx', null=True, upload_to='timetable/teachers')),
                ('teacher', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='timetable', to='teacherPortal.teacher')),
            ],
        ),
        migrations.CreateModel(
            name='Submission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answersheet', models.FileField(null=True, upload_to='submissions')),
                ('assignment', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='submission', to='teacherPortal.assignment')),
                ('student', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='submission', to='studentPortal.student')),
            ],
        ),
        migrations.AddField(
            model_name='assignment',
            name='teacher',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='assignment', to='teacherPortal.teacher'),
        ),
    ]
