# Generated by Django 3.2.2 on 2021-05-08 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacherPortal', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignment',
            name='is_open',
            field=models.BooleanField(default=True),
        ),
    ]
